python3: can't open file '/home/ubuntu/referto-backend/referto/manage.py': [Errno 2] No such file or directory
python3: can't open file '/home/ubuntu/referto-backend/referto/manage.py': [Errno 2] No such file or directory
